---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/23 上午12:14
---



---	["大碗茶"]={﻿ID="大碗茶",type="饮水",name="大碗茶",weight=50,unit="杯",description="一杯大碗茶，悠悠地冒着热气～～～",value=0,material="水",water=30,food=0,pice=3,actionA="喝",actionB="无",actionX="无",actionY="无",messageA="$N端起杯茶，有滋有味地品了几口。一股香气直入心脾，$N觉得精神好多了。",messageB="无",messageC="无",messageD="无",},



Food = Class("Food",GameObject)
--- 应该写在Actor 类里面。
--function Food:eat(actor)
--    actor.food = math.min(actor.food + self.food,actor.max_food)
--    actor.action = string.format("你拿起%s,吃了起来",self.name)
--end

function Food:update(dt)
    self.store_time = self.store_time + dt
    if self.store_time > self.max_store_time then
        self.state = "坏掉了"
    end
end