---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/22 下午10:19
---

require("lib.middleclass")

GameObject = Class("GameObject")

function GameObject:init(x,y,sets)
    self.x = x
    self.y = y
    local sets = sets or {}
    for k, v in pairs(sets) do
        self[k] = v
    end
    self.dead = false
end

function GameObject:update(dt)

end

function GameObject:draw()
    local w = self.w or 32
    local h = self.h or 32
    love.graphics.rectangle("fill",self.x,self.y,w,h)
end