---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/22 下午11:50
---
require("lib.animation")

Skill = Class("Skill",GameObject)

function Skill:draw()

end