---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/15 上午12:44
---

--- @class CreatStage : Stage
CreateStage = Class("CreateStage",Stage)

local style = {
    font = assets.font.myfont(32),
    showBorder = true,
    bgColor = {0.208, 0.220, 0.222,0.222},
    --fgColor = {1,0,0}
}

function CreateStage:init()
    self.area = Area(self)
    self.area:addPhysicsWorld()
    self.main_canvas = love.graphics.newCanvas(gw,gh)
    self.background = assets.graphics.Backgrounds.bg
    local title_font = assets.font.myfont(80)
    self.ui = gooi
    self.ui.desktopMode()
    self.ui_group = "CreateStage"
    --self.ui.desktopMode()
    --self.ui.shadow()
    --self.ui.setStyle({font = title_font})
    self.ui.newLabel({group = self.ui_group,text = "创建侠客",x = gw/3,y=gh/6}):center():setStyle({font=title_font}):fg({0,0,0})
    self.ui.setStyle(style)
    --gooi.glass()
    self.ui.newPanel()
    --self.ui.newButton({text = "新的穿越",x = 500,y = 500,w = 150,h = 36})
    --self.ui.newButton({text = "梦回武林",x = 500,y = 550,w = 150,h = 36})
    --self.ui.newButton({text = "侠客宝典",x = 500,y = 600,w = 150,h = 36})
    self.ui.newButton({group = self.ui_group,text = "返回太虚",x = gw - 200,y = gh - 100,w = 150,h = 36})
             :onRelease(
            function ()
                p_print("goto main")
                gotoRoom("MainStage","MainStage")
            end)
            --function()
            --    self.ui.confirm({group = self.ui_group,text = "梦醒",okText = "是",cancelText = "否"
            --    ,ok = function ()
            --            p_print("goto main")
            --            gotoRoom("MainStage","MainStage")
            --        end})
            --end
    --)
    --gooi.setCanvas(self.main_canvas)
end

function CreateStage:activate()
    self.ui.setGroupEnabled(self.ui_group,true)
    self.ui.setGroupVisible(self.ui_group,true)
end

function CreateStage:deactivate()
    self.ui.setGroupEnabled(self.ui_group,false)
    self.ui.setGroupVisible(self.ui_group,false)
end

function CreateStage:update(dt)
    if self.area then self.area:update(dt) end
    self.ui.update(dt)
end

function CreateStage:draw()
    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    camera:attach(0,0,gw,gh)
    love.graphics.draw(self.background)
    if self.area then self.area:draw() end
    camera:detach()
    love.graphics.setCanvas()

    love.graphics.setColor(1,1,1,1)
    love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,sx,sy)
    love.graphics.setBlendMode('alpha')
    self.ui.draw(self.ui_group)

end

function CreateStage:mousereleased()
    self.ui.released()
end

function CreateStage:mousepressed()
    self.ui.pressed()
end

function CreateStage:destroy()
    if self.area then
        self.area:destroy()
        self.area = nil
    end
end

return CreateStage