---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/15 上午12:44
---

--- @class CreatStage : Stage
CreatStage = Class("CreatStage",Stage)

--- init
local style = {
    font = assets.font.myfont(32),
    showBorder = false,
    bgColor = {0.208, 0.220, 0.222,0.222},
    --fgColor = {1,0,0}
}


function CreatStage:init()
    self.area = Area(self)
    self.area:addPhysicsWorld()
    self.main_canvas = love.graphics.newCanvas(gw,gh)
    self.background = assets.graphics.Backgrounds.bg
    local title_font = assets.font.myfont(80)
    self.ui = gooi
    self.ui.desktopMode()
    self.ui.shadow()
    self.ui.setStyle({font = title_font})
    self.ui.newLabel({text = "武侠与江湖",x = gw/3,y=gh/6}):fg({0,0,0}):center()
    self.ui.setStyle(style)
    --gooi.glass()
    self.ui.newPanel()
    b1 = self.ui.newButton({text = "新的穿越",x = 500,y = 500,w = 150,h = 36})
    b2 = self.ui.newButton({text = "梦回武林",x = 500,y = 550,w = 150,h = 36})
    b3 = self.ui.newButton({text = "侠客宝典",x = 500,y = 600,w = 150,h = 36})
    b4 = self.ui.newButton({text = "归隐山林",x = 500,y = 650,w = 150,h = 36})
             :onRelease(
            function()
                self.ui.confirm({text = "梦醒",okText = "是",cancelText = "否",ok = function () love.event.quit() end})
            end
    )
    --gooi.setCanvas(self.main_canvas)
end

function CreatStage:update(dt)
    if self.area then self.area:update(dt) end
    self.ui.update(dt)
end

function CreatStage:draw()
    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    camera:attach(0,0,gw,gh)
    love.graphics.draw(self.background)
    if self.area then self.area:draw() end
    camera:detach()
    love.graphics.setCanvas()

    love.graphics.setColor(1,1,1,1)
    love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,sx,sy)
    love.graphics.setBlendMode('alpha')
    self.ui.draw()

end

function CreatStage:mousereleased()
    self.ui.released()
end

function CreatStage:mousepressed()
    self.ui.pressed()
end

function CreatStage:destroy()
    if self.area then
        self.area:destroy()
        self.area = nil
    end
end

return CreatStage