---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/23 上午12:14
---
---	["大碗茶"]={﻿ID="大碗茶",type="饮水",name="大碗茶",weight=50,unit="杯",description="一杯大碗茶，悠悠地冒着热气～～～",value=0,material="水",water=30,food=0,pice=3,actionA="喝",actionB="无",actionX="无",actionY="无",messageA="$N端起杯茶，有滋有味地品了几口。一股香气直入心脾，$N觉得精神好多了。",messageB="无",messageC="无",messageD="无",},

--- @class Food
--- @type food

Food = Class("Food",GameObject)

--- 应该写在Actor 类里面。
--- 参照CDDA 写到物品中。人物只有一个动作，就是调用物品的功能，然后使用
function Food:getFromId(id)
    local foods = require("assets.data.objs")
    local food = foods[id]
    if food.type ~= "food" then
        error("not food")
    end
    for k,v in pairs(food) do
        print(tostring(k),tostring(v))
    end
    GameObject.init(self,0,0,food)
end

function Food:init(x,y,opts)
    GameObject.init(self,x,y,opts)
    self.info = {}
    local foods = require("assets.data.objs")
    if foods[opts.id] then
        local food = foods[opts.id]
        if food.type ~= "food" then
            error("not food")
        end
        for k,v in pairs(food) do
            self.info[k] = v
        end
    end
    self.info.store_time = 0
    self.info.max_store_time = 100
    self.info.state = "新鲜的"

    --self.infoPanel = InfoPanel.init(_,self.x,self.y,self.info)
end

function Food:eatby(actor)
    actor.food = math.min(actor.food + self.food,actor.max_food)
    actor.water = math.min(actor.water + self.water,actor.max_water)
    actor.action = string.format("%s拿起%s,吃了起来",actor.name,self.name)
    print(actor.action,actor.food)
end

function Food:update(dt)
    self.store_time = self.store_time + dt
    if self.store_time > self.max_store_time then
        self.state = "坏掉了"
    end
end

function Food:draw()
    love.graphics.rectangle("fill",self.x,self.y,32,32)
end

function Food:drawInfoPanel()
    local w,h = 200,400
    local x,y = 200,200
    local cell_x,cell_y = 20,20
    local cell = {}
    for x = 0, w/cell_x - 1 do
        cell[x] = {}
        for y = 0,h/cell_y - 1 do
            cell[x][y] = ""
        end
    end
    love.graphics.rectangle("line",x,y,w,h)
    love.graphics.print()
end
