---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/8/26 上午12:38
---
--- @class GameObject

GameObject = Class("GameObject")

--- @param opts table
--- @param area Area
--- @field area Area
--- @field timer Timer()
--- @field x number
--- @field y number
--- @field id UUID()
--- @field depth number

function GameObject:init(area,x,y,opts)
	local opts = opts or {}
    if opts then for k, v in pairs(opts) do self[k] = v end end

    self.area = area
    self.x = x
    self.y = y
    self.id = UUID()
    self.dead = false
    self.depth = 50
    self.timer = Timer()
    self.creation_time = os.time()
end

function GameObject:update(dt)
    if self.collider then self.x,self.y = self.collider:getPosition() end
	if self.timer then self.timer:update(dt) end
end

function GameObject:draw()
	 love.graphics.rectangle("fill",self.x,self.y,45,45)
end

function GameObject:destroy()
    self.timer:destroy()
    if self.collider then self.collider:destroy() end
    self.collider = nil
end

return GameObject