---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/6 上午10:55
---


--- @class InfoPanel
InfoPanel = Class("InfoPanel",GameObject)

--- @param area Area
--- @param x number
--- @param y number
--- @param opts table

function InfoPanel:init(area,x,y,opts)
    InfoPanel.super.init(self,area,x,y,opts)
    local opts = opts or {}
    --info = opts.info or
    self.w = 300
    local info = opts
    local info_max_h = 600
    self.text,info_max_h = objInfoText(info,text_style.font18,self.w)
    self.h = info_max_h or 400

    self.hover = false
end

function InfoPanel:update(dt)
    InfoPanel.super.update(self,dt)
    self.x,self.y = love.mouse.getX(),love.mouse.getY()
    --local m_x,m_y = love.mouse.getX(),love.mouse.getY()
    --if m_x > self.x and m_x < self.x + self.w and m_y > self.y and m_y < self.y + self.h then
    --    self.hover = true
    --end
end

function InfoPanel:draw()
    love.graphics.rectangleArcPanel(self.x,self.y,self.w,self.h)
    love.graphics.draw(self.text,self.x,self.y)
end


