---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/6 上午10:55
---


--- @class InfoPanel
InfoPanel = Class("InfoPanel",GameObject)

function InfoPanel:init(area,x,y,opts)
    InfoPanel.super.init(self,area,x,y,opts)
    local opts = opts or {}
    self.w,self.h = opts.w or 240,opts.h or 400
    --self.info = opts.info or {name = "罗汉拳秘籍",type = "书籍 / 秘籍",material = "纸",quality= 5,dur = 1,dur_max = 4,weight = 0.5,use_type = "习得",use = "罗汉拳",value = 3000,des = "一本武林秘籍，记载着少林寺罗汉拳。"}

    self.info = {name = "劣质金疮药",type = "物品 / 药丸",material = "药",quality= 9,dur = 1,dur_max = 2,weight = 0.1,use_type = "气血",use = "-50",value = 10,des = "治疗外伤的良药。"}

    self.rich_info = {}
    self.text = love.graphics.newText(text_style.font18)

    local q = 'q' .. tostring(self.info.quality)
    local r,line_h = 16,22
    local w = self.w - r * 2

    self.text:addf({text_style[q],self.info.name},w,'center',r,0)
    self.text:addf({text_style[q],quality_labels[self.info.quality]},w,'center',r,line_h)
    --self.text:addf({text_style["q10"],"价值 ",text_style["q5"],self.info.value},w,'right',r,line_h)

    --self.text:addf({text_style['q'..self.info.quality],self.info.type},w,'left',r,line_h * 2)
    local des_index = self.text:addf({text_style['q11'],self.info.des},w,'left',r,line_h * 2)
    local des_h = self.text:getHeight(des_index)

    self.text:addf({Color["橘黄"],"【道具类型】"},w,'left',r,line_h * 3 + des_h)
    self.text:addf({Color["棕灰"],"-类别：",Color["浅灰"],self.info.type},w,'left',r,line_h * 4 + des_h)
    self.text:addf({Color["棕灰"],"-材质：",Color["浅灰"],self.info.material},w,'left',r,line_h * 5 + des_h)
    self.text:addf({Color["棕灰"],"-耐久：",Color["红色"],self.info.dur,Color["棕灰"]," / ",Color["白色"],self.info.dur_max,Color["浅灰"]," (无法修复) "},w,'left',r,line_h * 6 + des_h)
    self.text:addf({Color["棕灰"],"-重量：",Color["浅灰"],self.info.weight},w,'left',r,line_h * 7 + des_h)
    self.text:addf({Color["浅灰"],"-无法精制"},w,'left',r,line_h * 8 + des_h)

    self.text:addf({Color["橘黄"],"【使用效果】"},w,'left',r,line_h * 10 + des_h)
    local color = Color["浅灰"]
    if  self.info.use:find("+") then
        color = Color["绿色"]
    elseif self.info.use:find("-") then
        color = Color["红色"]
    end
    self.text:addf({Color["浅灰"],"-"..self.info.use_type .. "：",color,self.info.use},w,'left',r,line_h * 11 + des_h)



    self.text:addf({text_style["q10"],"价值 ",text_style["q5"],self.info.value},w,'right',r,line_h * 15 + des_h)

end

function InfoPanel:update(dt)
    InfoPanel.super.update(self,dt)
    self.x,self.y = love.mouse.getX(),love.mouse.getY()
end

function InfoPanel:draw()
    local line_width = 2
    local r = 10
    local line_color = {0.8,0.8,0.8}
    local panel_color = {0.3,0.3,0.3,1}
    love.graphics.setLineWidth(line_width)
    love.graphics.setColor(panel_color)
    love.graphics.rectangle('fill',self.x,self.y,self.w,self.h,r * 2)
    love.graphics.setColor(line_color)
    love.graphics.line(self.x + r,self.y,self.x + self.w - r,self.y)
    love.graphics.line(self.x + r,self.y + self.h,self.x + self.w - r,self.y + self.h)
    love.graphics.line(self.x,self.y + r,self.x,self.y + self.h - r)
    love.graphics.line(self.x + self.w,self.y + r,self.x + self.w,self.y + self.h - r)

    love.graphics.arc('line','open',self.x,self.y,r,0,PI/2)
    love.graphics.arc('line','open',self.x + self.w,self.y,r,PI/2,PI)
    love.graphics.arc('line','open',self.x + self.w,self.y + self.h,r,PI,PI + PI/2)
    love.graphics.arc('line','open',self.x,self.y + self.h,r,PI + PI/2,PI * 2)

    love.graphics.setColor(1,1,1,0.3)
    love.graphics.setLineWidth(1)
    love.graphics.line(self.x + r,self.y + 43,self.x + self.w - r,self.y + 43)
    love.graphics.setColor(init_color)

    love.graphics.draw(self.text,self.x,self.y)
end

