---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/29 下午11:55
---

--- @class LoadStage : Stage
LoadStage = Class("LoadStage",Stage)

--- init
local style = {
    font = assets.font.myfont(32),
    showBorder = true,
    bgColor = {0.208, 0.220, 0.222,0.222},
    group = "LoadStage"
    --fgColor = {1,0,0}
}

require("lib.gooi")
function LoadStage:init()
    self.area = Area(self)
    self.main_canvas = love.graphics.newCanvas(gw,gh)
    self.background = assets.graphics.Backgrounds.bg
    self.ui = gooi
    self.ui.desktopMode()
    --- ui 切换
    self.ui_group = "LoadStage"
    self.ui.setStyle(style)
    self.ui.newLabel({text = "梦回武林",x = gw/2 - 320,y= 40,w = 320,group = self.ui_group}):setStyle({font = font80}):fg({0,0,0}):center()
    self.ui.newButton({group = self.ui_group,text = "返回太虚",x = gw - 400,y = gh - 100})
        :onRelease(
            function ()
                gotoRoom("MainStage","MainStage")
            end)
end

function LoadStage:activate()
    self.ui.setGroupVisible(self.ui_group,true)
    self.ui.setGroupEnabled(self.ui_group,true)
end

function LoadStage:deactivate()
    self.ui.setGroupVisible(self.ui_group,false)
    self.ui.setGroupEnabled(self.ui_group,false)
end

function LoadStage:update(dt)
    if self.area then self.area:update(dt) end
    self.ui.update(dt)
end

function LoadStage:draw()
    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    camera:attach(0,0,gw,gh)
    love.graphics.draw(self.background)
    if self.area then self.area:draw() end
    camera:detach()
    love.graphics.setCanvas()

    love.graphics.setColor(1,1,1,1)
    love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,sx,sy)
    love.graphics.setBlendMode('alpha')
    self.ui.draw(self.ui_group)


end

function LoadStage:mousereleased()
    self.ui.released()
end

function LoadStage:mousepressed()
    self.ui.pressed()
end

function LoadStage:destroy()
    if self.area then
        self.area:destroy()
        self.area = nil
    end
end

return LoadStage