---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/14 上午12:51
---

--- @class MainStage : Stage
MainStage = Class("MainStage",Stage)

--- init
local style = {
    font = assets.font.myfont(32),
    showBorder = true,
    bgColor = {0.208, 0.220, 0.222,0.222},
    --fgColor = {1,0,0}
}

require("lib.gooi")
function MainStage:init()
    self.area = Area(self)
    self.area:addPhysicsWorld()
    self.main_canvas = love.graphics.newCanvas(gw,gh)
    self.background = assets.graphics.Backgrounds.bg
    local title_font = assets.font.myfont(80)
    self.ui = gooi
    self.ui.desktopMode()
    self.ui_group = "MainStage"
    self.ui.setStyle({font = title_font})
    --self.panel = self.ui.newPanel({x = gw/2,y = hg/2,w = 200,h = 120,layout = "grid 4x1"})
    self.ui.newLabel({text = "武侠与江湖",x = gw/3,y=gh/6,group = self.ui_group}):fg({0,0,0}):center()
    self.ui.setStyle(style)
    --gooi.glass()
    --gooi.newPanel()
    self.ui.newButton({text = "新的穿越",x = 500,y = 500,w = 150,h = 36,group = self.ui_group})
            :onRelease(
            function()
                gotoRoom("CreateStage","CreateStage")
            end)
    self.ui.newButton({text = "梦回武林",x = 500,y = 550,w = 150,h = 36,group = self.ui_group})
    self.ui.newButton({text = "侠客宝典",x = 500,y = 600,w = 150,h = 36,group = self.ui_group})
    self.ui.newButton({text = "归隐山林",x = 500,y = 650,w = 150,h = 36,group = self.ui_group})
            :onRelease(
            function()
                p_print("Main")
                self.ui.confirm({group = self.ui_group,text = "梦醒",okText = "是",cancelText = "否",ok = function () love.event.quit() end})
            end
    )
    --self.area:addObject()
    --gooi.setCanvas(self.main_canvas)
end

function MainStage:activate()
    self.ui.setGroupVisible(self.ui_group,true)
    self.ui.setGroupEnabled(self.ui_group,true)
end

function MainStage:deactivate()
    self.ui.setGroupVisible(self.ui_group,false)
    self.ui.setGroupEnabled(self.ui_group,false)
end

function MainStage:update(dt)
    if self.area then self.area:update(dt) end
    self.ui.update(dt)
end

function MainStage:draw()
    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    camera:attach(0,0,gw,gh)
    love.graphics.draw(self.background)
    if self.area then self.area:draw() end
    camera:detach()
    love.graphics.setCanvas()

    love.graphics.setColor(1,1,1,1)
    love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,sx,sy)
    love.graphics.setBlendMode('alpha')
    self.ui.draw(self.ui_group)

end

function MainStage:mousereleased()
    self.ui.released()
end

function MainStage:mousepressed()
    self.ui.pressed()
end

function MainStage:destroy()
    if self.area then
        self.area:destroy()
        self.area = nil
    end
end

return MainStage