---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/10/14 上午12:51
---

--- @class MainStage : Stage
MainStage = Class("MainStage",Stage)

--- init
local style = {
    font = assets.font.myfont(32),
    showBorder = false,
    bgColor = {0.208, 0.220, 0.222,0.222},
    --fgColor = {1,0,0}
}


function MainStage:init()
    self.area = Area(self)
    self.area:addPhysicsWorld()
    self.main_canvas = love.graphics.newCanvas(gw,gh)
    self.background = assets.graphics.Backgrounds.bg
    local title_font = assets.font.myfont(80)
    gooi.desktopMode()
    gooi.shadow()
    gooi.setStyle({font = title_font})
    gooi.newLabel({text = "武侠与江湖",x = gw/3,y=gh/6}):fg({0,0,0}):center()
    gooi.setStyle(style)
    --gooi.glass()
    gooi.newPanel()
    b1 = gooi.newButton({text = "新的穿越",x = 500,y = 500,w = 150,h = 36})
            :onRelease(
            function()
                gotoRoom("CreatStage","CreatStage")
            end)
    b2 = gooi.newButton({text = "梦回武林",x = 500,y = 550,w = 150,h = 36})
    b3 = gooi.newButton({text = "侠客宝典",x = 500,y = 600,w = 150,h = 36})
    b4 = gooi.newButton({text = "归隐山林",x = 500,y = 650,w = 150,h = 36})
            :onRelease(
            function()
                gooi.confirm({text = "梦醒",okText = "是",cancelText = "否",ok = function () love.event.quit() end})
            end
    )
    --gooi.setCanvas(self.main_canvas)
end

function MainStage:update(dt)
    if self.area then self.area:update(dt) end
    gooi.update(dt)
end

function MainStage:draw()
    love.graphics.setCanvas(self.main_canvas)
    love.graphics.clear()
    camera:attach(0,0,gw,gh)
    love.graphics.draw(self.background)
    if self.area then self.area:draw() end
    camera:detach()
    love.graphics.setCanvas()

    love.graphics.setColor(1,1,1,1)
    love.graphics.setBlendMode('alpha','premultiplied')
    love.graphics.draw(self.main_canvas,0,0,0,sx,sy)
    love.graphics.setBlendMode('alpha')
    gooi.draw()

end

function MainStage:mousereleased()
    gooi.released()
end

function MainStage:mousepressed()
    gooi.pressed()
end

function MainStage:destroy()
    if self.area then
        self.area:destroy()
        self.area = nil
    end
end

return MainStage