-- 窗口配置表格文件
guiData={
	["头像"]={visible=true,type="image",x=0,y=0,width=192,height=192,contant="",color="RED",image=nil},
	["世家"]={visible=true,type="txt",x=100,y=0,contant="",color=""},
	["称号"]={visible=true,type="txt",x=100,y=20,contant="",color=""},
	["名称"]={visible=true,type="txt",x=100,y=40,contant="",color=""},
	["气血"]={visible=true,title="气血",type="bar",x=100,y=60,contant="0",color="RED"},
	["真气"]={visible=true,title="真气",type="bar",x=100,y=80,contant="0",color="BLUE"},
	["精力"]={visible=true,type="txt",x=100,y=100,contant="",color="RED"},
	["食物"]={visible=true,type="txt",x=100,y=140,contant="",color="RED"},
	["饮水"]={visible=true,type="txt",x=100,y=160,contant="",color="RED"},
	["国家"]={visible=true,type="txt",x=100,y=180,contant="",color="RED"},
	["门派"]={visible=true,type="txt",x=100,y=200,contant="",color="RED"},
	["区域"]={visible=true,type="txt",x=100,y=220,contant="",color="RED"},
	["技能1"]={visible=true,type="txt",x=100,y=760,contant="",color="RED"},
	["技能2"]={visible=true,type="txt",x=300,y=760,contant="",color="RED"},
	["技能3"]={visible=true,type="txt",x=500,y=760,contant="",color="RED"},
	["技能4"]={visible=true,type="txt",x=700,y=760,contant="",color="RED"},
	["区域"]={visible=true,type="txt",x=400,y=20,contant="",color="GREEN"},
	["房间"]={visible=true,type="txt",x=500,y=20,contant="",color="GREEN"},
	["描述"]={visible=true,type="long",x=8,y=160,width=280,height=200,alpha=64,contant="",color=nil},
	-- ["时间"]={visible=true,type="txt",x=500,y=0,contant="虎年 十二月 十日 子时 晴朗",color=nil},
	["对话"]={visible=true,type="dialog",x=500,y=160,width=280,height=100,alpha=64,contant="对话测试文本这是一段长文本的对话测试",color="WHITE",image=nil},
	["地图"]={visible=true,title="测试",type="map",x=1080,y=0,width=200,height=200,alpha=64,contant="",color=nil},
	["技能"]={visible=true,type="skill",x=4,y=752,width=1280,height=48,alpha=64,contant="技能栏测试",align="center",color=nil,image=nil},
	["发现"]={visible=true,type="txt",x=440,y=40,contant="",color=nil},
	["坐标"]={visible=true,type="txt",x=240,y=40,contant="",color=nil},
	["信息"]={visible=true,type="long",x=8,y=400,width=280,height=340,alpha=64,contant="",color=nil},
}

return guiData